tximistacliente1_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: 'tximistacliente1UserBundle:Default:index' }
admin_access:
    path:     /admin
    defaults: { _controller: 'tximistacliente1UserBundle:Default:admin' }
